name: 🚀 Deploy on push main

on:
  push:
    branches:
      - main
env:
  NEXT_PUBLIC_API: ${{ secrets.NEXT_PUBLIC_API }}
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
      - name: list output folder server
        run: find server/ -print
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.dijaminhoki-ads.site
          username: vads01api@vads01api.dijaminhoki-ads.site
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: server/
          exclude: |
            **/.git*
            **/.git*/**
             **/node_modules/**
